//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 

using Experity.SprintDashboard.Data.GenPro.Entities.EntityClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;

namespace Experity.SprintDashboard.Data.GenPro.Entities.FactoryClasses
{
    /// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
    public partial class QueryFactory : QueryFactoryBase2
    {
        /// <summary>Creates and returns a new EntityQuery for the Clinic entity</summary>
        public EntityQuery<ClinicEntity> Clinic { get { return Create<ClinicEntity>(); } }

        /// <summary>Creates and returns a new EntityQuery for the Conversation entity</summary>

        /// <summary>Creates and returns a new EntityQuery for the LogDetail entity</summary>

        /// <summary>Creates and returns a new EntityQuery for the Practice entity</summary>
        public EntityQuery<PracticeEntity> Practice { get { return Create<PracticeEntity>(); } }

        /// <summary>Creates and returns a new EntityQuery for the QueueType entity</summary>

        /// <inheritdoc/>
        protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }

    }
}