//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////

using Experity.SprintDashboard.Data.GenPro.Entities.EntityClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Experity.SprintDashboard.Data.GenPro.Entities.HelperClasses
{
    /// <summary>Field Creation Class for entity ClinicEntity</summary>
    public partial class ClinicFields
    {
        /// <summary>Creates a new ClinicEntity.ClinicPk field instance</summary>
        public static EntityField2 ClinicPk { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ClinicFieldIndex.ClinicPk); } }
        /// <summary>Creates a new ClinicEntity.Name field instance</summary>
        public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ClinicFieldIndex.Name); } }
        /// <summary>Creates a new ClinicEntity.PracticePk field instance</summary>
        public static EntityField2 PracticePk { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ClinicFieldIndex.PracticePk); } }
        /// <summary>Creates a new ClinicEntity.UtcOffset field instance</summary>
        public static EntityField2 UtcOffset { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ClinicFieldIndex.UtcOffset); } }
    }

    /// <summary>Field Creation Class for entity PracticeEntity</summary>
    public partial class PracticeFields
    {
        /// <summary>Creates a new PracticeEntity.Environment field instance</summary>
        public static EntityField2 Environment { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PracticeFieldIndex.Environment); } }
        /// <summary>Creates a new PracticeEntity.Practice field instance</summary>
        public static EntityField2 Practice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PracticeFieldIndex.Practice); } }
        /// <summary>Creates a new PracticeEntity.PracticePk field instance</summary>
        public static EntityField2 PracticePk { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PracticeFieldIndex.PracticePk); } }
    }
}