//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////

namespace Experity.SprintDashboard.Data.GenPro.Sql
{
    /// <summary>Class which contains the static logic to execute retrieval stored procedures in the database.</summary>
    public static partial class RetrievalProcedures
    {



    }
}
